version: 2.1
jobs:
  Run-Test:
    docker:
      - image: cimg/base:stable
    resource_class: large  
    steps:
      - checkout
      - run:
          name: "Say hello "
          command: "echo Run Test"
          
workflows:
  version: 2
  build_and_deploy_dev2:
    jobs:
      - Run-Test:
          filters:
            branches:
              only: develop
  build_and_deploy_prod2:
    jobs:
      - Run-Test:
          filters:
            branches:
              only: prod
  build_and_deploy_master:
    jobs:
      - Run-Test:
          filters:
            branches:
              only: master
