version: 2.1
jobs:
  Test-Dev:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "ech Hello, World! Dev"


  Test-Prod:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World! Prod" 


  Test-Master:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World! Master"  
workflows:
  version: 2
  build_and_deploy_dev2:
    jobs:
      - Test-Dev:
          filters:
            branches:
              only: develop
  build_and_deploy_prod2:
    jobs:
      - Test-Prod:
          filters:
            branches:
              only: prod
  build_and_deploy_master2:
    jobs:
      - Test-Master:
          filters:
            branches:
              only: master
