version: 2.1
jobs:
  Run-Test-Dev:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello "
          command: "echo Hello, World! Dev"

workflows:
  version: 2
  build_and_deploy_dev2:
    jobs:
      - Run-Test-Dev:
          filters:
            branches:
              only: develop
  build_and_deploy_prod2:
    jobs:
      - Run-Test-Prod:
          filters:
            branches:
              only: prod
  build_and_deploy_master:
    jobs:
      - Run-Test-Master:
          filters:
            branches:
              only: master
