# This is a basic workflow to help you get started with Actions    

name: CI

on:
#   push:
#     branches:
#       - master
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      ENV: Enable
    steps:
      - uses: actions/checkout@v2
      - name: Try to fail
        if: ${{ env.ENV == 'Enable1' }}
        run: exit 1
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
