# This is a basic workflow to help you get started with Actions    

name: CI

on:
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      check_deploy: ${{ secrets.RUN_CI_DEPLOY }}
    steps:
      - name: Try to fail
        if: ${{ env.check_deploy != 'false' }}
        run: exit 1
 
